:set nu
:set tabstop=4
:set shiftwidth=4
:set expandtab
:set softtabstop=4
:set autoindent
:set noswapfile
:set mouse=in
:syntax on
:set nocp
:set encoding=utf-8
:set hlsearch
:set backspace=indent,eol,start
:hi Search cterm=None ctermfg=black ctermbg=LightMagenta
nnoremap q: <nop>
nnoremap Q <nop>
